force-app/main/default/objects/ApexHealth__c/ApexHealth__c.object-meta.xml
<CustomObject>
    <label>Apex Health</label>
    <nameField>
        <displayFormat>AH-{000000}</displayFormat>
        <label>Apex Health Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Health</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexHealth__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <label>Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexHealth__c/fields/LoadId__c.field-meta.xml
<CustomField>
    <fullName>LoadId__c</fullName>
    <description>It specifies the unique id for each load of apex health data</description>
    <inlineHelpText>It specifies the unique id for each load of apex health data</inlineHelpText>
    <label>Load Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/LoadId__c.field-meta.xml
<CustomField>
    <fullName>LoadId__c</fullName>
    <label>Load Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexHealth_BAT_DeletePreviousDataTest.cls
/**
* @description       : Test class for ApexHealth_BAT_DeletePreviousData
* @author            : Goutham Cheedella/ Logesh M
* @project           : ApexPulse
* @last modified on  : 07-30-2024
* @last modified by  : gcheedella@salesforce.com
**/
@isTest
public class ApexHealth_BAT_DeletePreviousDataTest {
    
    /**
    * @description testBatchClass
    */
    @isTest
    public static void testBatchClass() {
        
        User testUser = ApexHealthTestUtility.createUserWithPermissionSet();
        System.runAs(testUser){
            String loadId ='1234567890';
            List<ApexClass> apexClassList = [Select Id from ApexClass Where Namespaceprefix = NULL Limit 2];
            
            List<String> apexClassIds = new List<String>();
            
            for(ApexClass apxc: apexClassList){
                apexClassIds.add(apxc.Id);
            }
            if(apexClassList.size() > 0){
                ApexHealth__c apexHealthrecord = new ApexHealth__c(LoadId__c = '1234567800', EntityId__c = apexClassList[0].Id );        
                insert apexHealthrecord;  
            }
            // Verify expected results
            List<ApexHealth__c> insertedapHRecords = [SELECT Id, Name, LoadId__c FROM ApexHealth__c WHERE LoadId__c !=: loadId];
            Logger__c logRecord = new Logger__c();
            logRecord.LoadId__c = '1234567890';
            insert logRecord;
            Test.startTest();
            // Execute the batch class
            ApexHealth_BAT_DeletePreviousData batch = new ApexHealth_BAT_DeletePreviousData(loadId, apexClassIds);
            Database.QueryLocator ql = batch.start(null);
            batch.execute(null,apexClassList);
            batch.Finish(null);
            Test.stopTest();
            System.assertNotEquals(null, logRecord);
        }
    }
}